name: TAS Tests

on:
  push:
    branches: 
      - main
  schedule:
    - cron: '2 0 * * *'  # daily UTC - 2AM

jobs:
  run-tas:
    name: Run TAS Games Tests
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.42.1-focal
    env:
      HEADLESS: true   # ensure headless browsers

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Run Games tests
        run: npm run testGames
